name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GO_VERSION: 1.16

jobs:
  # run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      # The paths-filter action requires a checkout step for push events.
      - if: ${{ github.event_name == 'push' }}
        uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            frontend:
              - 'src/frontend/**'

  build:
    runs-on: ubuntu-latest
    needs: [ changes ]
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build frontend image
        if: ${{ needs.changes.outputs.frontend == 'true' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: sd-foobar-org/microservice-demo-frontend:${{ github.sha }}
          